
# Licensed under GNU Lesser General Public License v3.0

# install: conda env create -f conda_env.yaml 
# update:  conda env update -f conda_env.yaml 

dependencies:
  - python=3.8
  - pip
  - numpy
  - opencv
  - pip:
    - -r requirements.txt

